### ISSUE TITLE
Use webview-bridge in iOS app

### ISSUE THREAD

**Issue by jprojashernandez** [tef-dig/webview-bridge#16]
Hi there,

I want to use webview bridge in my angular page and open it from my iOS app. But when I call isWebViewBridgeAvailable method in my page, it always returns false.

What am I doing wrong?

Thanks in advance.

**Comment by pladaria** [comment]
Hi, 

Thank you for your interest. To use this bridge you need to implement the native part and create a message handler.

See https://developer.apple.com/documentation/webkit/wkusercontentcontroller/1537172-addscriptmessagehandler?language=objc
